### PR TITLE
Update the footer 

### PR DESCRIPTION
**Pull request by Ishaan28malik**
### Please ensure Checkmark the following :

- [x] - Tested Localy
- [x] - Checked in IE11 and Firefox
- [x] - Checked in mobile
- [x] - Backend work
- [x] - Frontend work
- [ ] - Bug Fixes
- [x] - Enhancements

### CODE REVIEW

**Comment by Wynnfan** [comment]
Your commit does not match the style shown below image.

**Comment by Ishaan28malik** [comment]
@Wynnfan I suppose u didn't check it by running locally on your system, it does look like this
image

**Comment by Wynnfan** [comment]
> @Wynnfan I suppose u didn't check it by running locally on your system, it does look like this
> image
> 
> Maybe you were not able to see the changes because of the conflicts? @Wynnfan

My local style is good and doesn't need any changes, it just seems like dashboard.casbin.org has a problem.

**Comment by hsluoyz** [comment]
Footer fixed.

**Pull request closed without merging**
