### PR TITLE
added default minLength maxLength to id and name

### PR DESCRIPTION
**Pull request by shakti97**
Fix issue #27

### CODE REVIEW

**Comment by RoLoDeXx** [comment]
Majority of your code updates consist of indentation and prettier fixes, this can cause merge conflicts with people working on the same code base. I think you should tweak your code base to add an exception to that. Hope this helps :)

**Comment by hsluoyz** [comment]
Agree with @RoLoDeXx

**Comment by shakti97** [comment]
@hsluoyz actually the default prettier and eslint does that, should I make another pr with only required changes?

**Comment by hsluoyz** [comment]
Yes

**Pull request closed without merging**
