### PR TITLE
Updating the friendly policy management UI

### PR DESCRIPTION
**Pull request by Ishaan28malik**
This is with respect to the #55 issue, the UI can be modified as per the need and also they can be transformed into higher-level interfaces or lower-level interfaces as per the need and Dashboard up-gradation.

### Description: Adding  Some terms like "User Management", "Role Management", "Permission Management" are more friendly to users.

Added "User Management", "Role Management", "Permission Management" pages in the Menu

### Screenshot of changes :
header

### Please ensure Checkmark the following :

- [x] - Tested Localy
- [x] - Checked in IE11 and Firefox
- [x] - Checked in mobile
- [x] - Backend work
- [x] - Frontend work
- [x] - Bug Fixes
- [x] - Enhancements

### CODE REVIEW

**Comment by Ishaan28malik** [comment]
@hsluoyz Please review this.

**Comment by hsluoyz** [comment]
Please provide a demo site

**Comment by hsluoyz** [comment]
They are just menu bar items.

**Comment by Ishaan28malik** [comment]
Okay will update u with the demo

**Pull request closed without merging**
