### PR TITLE
spelling error in auth.js file

### PR DESCRIPTION
**Pull request by MehtaManan07**
### Description :

There was a small spelling error in the auth.js file in react js, I have corrected the spelling of the same and everywhere it was imported

### Please ensure Checkmark the following :

* [x] - Tested Localy
* [x] - Checked in IE11 and Firefox
* [x] - Checked in mobile
* [x] - Backend work
* [x] - Frontend work
* [x] - Bug Fixes
* [x] - Enhancements

### CODE REVIEW

**Comment by arteevraina** [comment]
@MehtaManan07 Please sign off your commit and add the issue number if any in the PR. The rest looks good to me.

**Comment by MehtaManan07** [comment]
> @MehtaManan07 Please sign off your commit and add the issue number if any in the PR. The rest looks good to me.

Can you please tell me how can I do that, I am not very sure what needs to done

**Comment by arteevraina** [comment]
@MehtaManan07 This will help.
https://github.com/casbin/casbin-dashboard/pull/131/checks?check_run_id=1213073912

**Comment by MehtaManan07** [comment]
> @MehtaManan07 This will help.
> https://github.com/casbin/casbin-dashboard/pull/131/checks?check_run_id=1213073912

Thank you so much

**Comment by nodece** [comment]
LGTM

**Review by nodece — APPROVED** [review]

**Pull request merged**
