### PR TITLE
Adding ESLint to the project

### LINKED ISSUE #18: Codebase should be integrated with Prettier and Eslint
**Additional Information**
I am working on it .

### PR DESCRIPTION
**Pull request by ani4aniket**
This PR adds ESLint to the web client for better code maintenance also cleaner code.

Fixes #18

### CODE REVIEW

**Comment by aryamanpuri** [comment]
@ani4aniket Have you not read I was working on it?

**Comment by ani4aniket** [comment]
Hello @aryamanpuri, I think you have just created an issue regarding that. I just set up the ESLint within the project, you may now take up fixing lint issues.

**Comment by aryamanpuri** [comment]
It was written on the top

**Comment by hsluoyz** [comment]
Wrong commits.

**Pull request closed without merging**
