### PR TITLE
Update App.js

### LINKED ISSUE #10: Update Readme
Instead of using React Boilerplate Readme, 
we should use write manual Readme consisting of how to setup and start the project .

### PR DESCRIPTION
**Pull request by 438561537**
### Description : 

fix #10 to avoid some warnings in the console.

### Please ensure Checkmark the following :

- [x]  Tested Localy
- [x]  Checked in IE11 and Firefox
- [ ]  Checked in mobile
- [ ]  Backend work
- [x]  Frontend work
- [x]  Bug Fixes
- [ ]  Enhancements

### CODE REVIEW

**Comment by hsluoyz** [comment]
@438561537 the PR message needs to be improved.

1. Write like `Fix #XX`, your words are not recognized by GitHub.
2. Don't include unnecessary screenshots. Provide links.
3. Your checkmarks are not in correct style.

@BetaCat0 can you help him make it right?

**Comment by BetaCat0** [comment]
@hsluoyz Yes. @438561537 Once you finish your work, please assign me for code reviewing :)

**Comment by 438561537** [comment]
@hsluoyz @BetaCat0 Sorry for these problems caused by wrong operation. Next time i may seriously check the operation and looking for your help.

**Comment by hsluoyz** [comment]
@438561537 `Fix #XX` is still not fixed. No brackets.

**Comment by 6ecuk** [comment]
@438561537 Your pull request wasn't merged in master

**Comment by hsluoyz** [comment]
@6ecuk please reivew.

**Comment by 6ecuk** [comment]
I checked yesterday and warning in the console is gone

**Comment by 438561537** [comment]
@6ecuk Thanks, thanks for your your attention.

**Pull request merged**
