### PR TITLE
Optimize the UI

### LINKED ISSUE #69: Fotter is not at bottom
Footer is not fixed at the bottom.

### PR DESCRIPTION
**Pull request by 438561537**
### Description :

- fix #69 #84 #82 #71 #69 #58  

- The Policy Page still needs to enhance. [Add Editor like](https://casbin.org/en/editor)

- Needs syntax and semantics check in add and edit pages.

### Please ensure Checkmark the following :

- [x] - Tested Localy
- [x] - Checked in IE11 and Firefox
- [ ] - Checked in mobile
- [x] - Backend work
- [x] - Frontend work
- [x] - Bug Fixes
- [x] - Enhancements

### CODE REVIEW

**Comment by 438561537** [comment]
Please review @BetaCat0 @GopherJ

**Comment by hsluoyz** [comment]
@438561537 please resolve conflicts.

**Comment by 438561537** [comment]
@hsluoyz The conflicts has been fixed.

**Comment by hsluoyz** [comment]
@438561537 please avoid making so big PR next time.

**Comment by 438561537** [comment]
@hsluoyz OK my mentor

**Pull request closed without merging**
