### PR TITLE
Refactor Table to fit full width available

### PR DESCRIPTION
**Pull request by shakti97**
This pr will close issue #40 and #41

### CODE REVIEW

**Comment by shakti97** [comment]
@hsluoyz have a look & suggest changes required :)

**Comment by anishagg17** [comment]
@shakti97 Please send some screenshots of change too

**Comment by hsluoyz** [comment]
Show demo or pictures.

**Comment by shakti97** [comment]
Before 
Screenshot from 2020-03-12 08-16-39

After
Screenshot from 2020-03-12 08-18-55

Before
Screenshot from 2020-03-12 08-19-16

After
Screenshot from 2020-03-12 08-20-06

**Comment by hsluoyz** [comment]
lgtm.

**Pull request merged**
