### PR TITLE
refactor frontend

### LINKED ISSUE #69: Fotter is not at bottom
Footer is not fixed at the bottom.

### PR DESCRIPTION
**Pull request by 438561537**
### Description :

- Fixed the latest pr [#86 ] for better reviewing. You can check [casbin-dashboard](dashboard.casbin.org) for this modified code.

- fix #69 #84 #82 #71 #69 #58  

- The Policy Page still needs to enhance. [Add Editor like](https://casbin.org/en/editor)

- Needs syntax and semantics check in add and edit pages.

### Please ensure Checkmark the following :

- [x] - Tested Localy
- [x] - Checked in IE11 and Firefox
- [ ] - Checked in mobile
- [x] - Backend work
- [x] - Frontend work
- [x] - Bug Fixes
- [x] - Enhancements

### CODE REVIEW

**Comment by hsluoyz** [comment]
Don't show `Update App.css Signed-off-by: 顾晓阳 <guxiaoyang@bupt.edu.cn>` in commit message.

**Comment by hsluoyz** [comment]
@BetaCat0

**Comment by hsluoyz** [comment]
Please fix only one issue in one PR.

**Comment by 438561537** [comment]
@hsluoyz OK

**Comment by andyyumiao** [comment]
> @hsluoyz OK

Do you have documentation for the web system？

**Pull request closed without merging**
