### PR TITLE
Fixed warnings

### LINKED ISSUE #83: update the Tables
### A suggestion
When we add a new model/adapter/enforcer, we hope the new row to be the first row of the table(not the last row). It may be convenient for us to add a lot of rows and divide them into many pages.

### PR DESCRIPTION
**Pull request by 438561537**
### Description :

1. fix #83  ,The warning(caused by the neglection of rowkey in tables) has been fixed.
2. The new row we add has been put onto the top of the tables for future management.
### Please ensure Checkmark the following :

- [x] - Tested Localy
- [x] - Checked in IE11 and Firefox
- [ ] - Checked in mobile
- [ ] - Backend work
- [x] - Frontend work
- [x] - Bug Fixes
- [ ] - Enhancements

### CODE REVIEW

**Comment by hsluoyz** [comment]
Please fix DCO first.

**Comment by 6ecuk** [comment]
@438561537 add reviwers

**Comment by 438561537** [comment]
@hsluoyz Please review.

**Comment by 438561537** [comment]
@BetaCat0 @GopherJ

**Comment by BetaCat0** [comment]
LGTM

**Comment by BetaCat0** [comment]
Thanks @438561537

**Comment by hsluoyz** [comment]
Is there a demo?

**Pull request merged**
